#cloud-config

yum_repos:
  ${mongodb_package}-${mongodb_version}:
    name: MongoDB Repository
    baseurl: https://${repo_url}/yum/amazon/2/${mongodb_package}/${mongodb_version}/$basearch/
    enabled: true
    gpgcheck: true
    gpgkey: https://www.mongodb.org/static/pgp/server-${mongodb_version}.asc

package_update: true
packages:
  - jq
  - ${mongodb_package}-shell

%{ if fqdn != null ~}
fqdn: ${fqdn}
preserve_hostname: false
%{ endif ~}


%{ if authorized_key != "" ~}
ssh_authorized_keys:
  - ${authorized_key}
%{ endif ~}

fs_setup:
  - label: mongodata
    filesystem: xfs
    device: /dev/${data_block_device}
    overwrite: false

mounts:
  - [ ${data_block_device}, ${mount_point}, "xfs", "defaults,nofail,noatime", "0", "2" ]

write_files:
  - content: |
      vm.swappiness=1
      vm.zone_reclaim_mode=0
    path: /etc/sysctl.d/90-mongod.conf
  - encoding: b64
    content: ${disable_thp_service}
    path: /etc/systemd/system/disable-thp.service
  - encoding: b64
    content: ${readahead_service}
    path: /etc/systemd/system/readahead.service
  - encoding: b64
    content: ${mongodb_nproc}
    path: /etc/security/limits.d/99-mongodb-nproc.conf
  - encoding: b64
    content: ${bootstrap}
    path: /var/lib/cloud/scripts/bootstrap.sh
    permissions: '0700'
  - content: ${genkey}
    path: /etc/mongodb-mms/gen.key
    permissions: '0600'
  - encoding: b64
    content: ${conf_mms}
    path: /var/lib/cloud/scripts/conf-mms.properties
  - encoding: b64
    content: ${cert_pem}
    path: /etc/mongodb-mms/opsmgr.pem
    permissions: '0600'
  - encoding: b64
    content: ${ca_cert_pem}
    path: /etc/mongodb-mms/ca.crt
    permissions: '0600'

runcmd:
  - [ sysctl, -p, /etc/sysctl.d/90-mongod.conf ]
  - [ systemctl, daemon-reload ]
  - [ systemctl, enable, disable-thp.service ]
  - [ systemctl, start, disable-thp.service ]
  - [ systemctl, enable, readahead.service ]
  - [ systemctl, start, readahead.service ]
  - /var/lib/cloud/scripts/bootstrap.sh install '${download_url}'
  - mkdir -p ${mount_point}/head
  - chown mongodb-mms:mongodb-mms -R ${mount_point}/head
  - cp /var/lib/cloud/scripts/conf-mms.properties /opt/mongodb/mms/conf/conf-mms.properties
  - chown mongodb-mms:mongodb-mms /opt/mongodb/mms/conf/conf-mms.properties
  - chown mongodb-mms:mongodb-mms -R /etc/mongodb-mms
  - [ systemctl, enable, mongodb-mms ]
  - [ systemctl, start, mongodb-mms ]

final_message: "Cloud Init complete!"