#cloud-config

package_update: true
packages:
  - jq
  - cyrus-sasl
  - cyrus-sasl-gssapi
  - cyrus-sasl-plain
  - krb5-libs
  - libcurl
  - net-snmp
  - openldap
  - openssl
  - xz-libs
  - curl

%{ if fqdn != null ~}
fqdn: ${fqdn}
preserve_hostname: false
%{ endif ~}

%{ if authorized_key != "" ~}
ssh_authorized_keys:
  - ${authorized_key}
%{ endif ~}

fs_setup:
  - label: mongodata
    filesystem: xfs
    device: /dev/${data_block_device}
    overwrite: false

mounts:
  - [ ${data_block_device}, ${mount_point}, "xfs", "defaults,nofail,noatime", "0", "2" ]

write_files:
  - content: |
      vm.swappiness=1
      vm.zone_reclaim_mode=0
    path: /etc/sysctl.d/90-mongod.conf
  - encoding: b64
    content: ${disable_thp_service}
    path: /etc/systemd/system/disable-thp.service
  - encoding: b64
    content: ${readahead_service}
    path: /etc/systemd/system/readahead.service
  - encoding: b64
    content: ${mongodb_nproc}
    path: /etc/security/limits.d/99-mongodb-nproc.conf

runcmd:
  - [ yum, update, -y]
  - [ sysctl, -p, /etc/sysctl.d/90-mongod.conf ]
  - [ systemctl, daemon-reload ]
  - [ systemctl, enable, disable-thp.service ]
  - [ systemctl, start, disable-thp.service ]
  - [ systemctl, enable, readahead.service ]
  - [ systemctl, start, readahead.service ]
  - [ mkdir, /etc/mongodb ]
  - [ curl, -L, "${server_cert_url}", -o, /etc/mongodb/server.pem ]
  - [ curl, -L, "${client_cert_url}", -o, /etc/mongodb/client.pem ]
  - [ curl, -L, "${ca_cert_url}", -o, /etc/mongodb/ca.crt ]
  - [ cp, /etc/mongodb/ca.crt, /etc/pki/ca-trust/source/anchors ]
  - [ update-ca-trust ]

final_message: "Cloud Init complete!"